# Generated by Django 5.2.2 on 2025-06-10 00:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('word', 'Word'), ('image', 'Image'), ('color', 'Color'), ('shape', 'Shape')], max_length=20)),
                ('prompt', models.CharField(max_length=255)),
                ('correct_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_category', models.CharField(max_length=50)),
                ('correct', models.BooleanField()),
                ('reaction_time', models.FloatField(help_text='Time in seconds')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.challenge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
    ]
