# Generated by Django 5.2.4 on 2025-09-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_challenge_gamesession'),
    ]

    operations = [
    ]
