# Generated by Django 5.2.4 on 2025-09-10 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20250909_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='📦', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='challenge',
            name='time_limit',
            field=models.FloatField(default=5.0, help_text='Time limit in seconds'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='avatar',
            field=models.CharField(default='🎮', max_length=50),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='best_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='experience_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='total_correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('word', 'Word Recognition'), ('image', 'Image Recognition'), ('color', 'Color Recognition'), ('shape', 'Shape Recognition'), ('emoji', 'Emoji Recognition'), ('number', 'Number Recognition')], max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='incorrect_categories',
            field=models.ManyToManyField(blank=True, related_name='incorrect_challenges', to='game.category'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='correct_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_challenges', to='game.category'),
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('total_challenges', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('average_reaction_time', models.FloatField(default=0.0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
    ]
